name: docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      version:
        description: Application version to use when publishing the project
        required: false
      image-tag:
        description: Additional Docker image tag to apply on deployment
        required: false

jobs:
  # Determine version
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Output GitHub event payload
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Payload: ${{ toJson(github.event) }}"
          echo "Prelelease: ${{ github.event.release.prerelease == true }}
